const DEFAULT_PLAYERS = [
  { id:1,    name:'Dominik Riedl',               gender:'male',   tier:'silver',   points:41.5,   gain:3,     played:15,  streak:0, bp:0, change:0  },
  { id:2,    name:'Julian Schönweger',           gender:'male',   tier:'silver',   points:35,     gain:2.5,   played:13,  streak:0, bp:0, change:0  },
  { id:3,    name:'Arzun',                       gender:'male',   tier:'silver',   points:35,     gain:3.5,   played:14,  streak:0, bp:0, change:0  },
  { id:4,    name:'Flo Kögl',                    gender:'male',   tier:'silver',   points:33,     gain:2,     played:12,  streak:0, bp:0, change:0  },
  { id:5,    name:'Büsra Gedik',                 gender:'female', tier:'silver',   points:33,     gain:2.5,   played:14,  streak:0, bp:0, change:0  },
  { id:6,    name:'Heinrich Wögerbauer',         gender:'male',   tier:'silver',   points:33,     gain:2.5,   played:14,  streak:0, bp:0, change:0  },
  { id:7,    name:'Magdalena Malli',             gender:'female', tier:'silver',   points:32.5,   gain:2.5,   played:11,  streak:0, bp:0, change:0  },
  { id:8,    name:'Ilvy Ladstätter',             gender:'female', tier:'silver',   points:32,     gain:3,     played:14,  streak:0, bp:0, change:0  },
  { id:9,    name:'Silke Kögl',                  gender:'female', tier:'silver',   points:31.5,   gain:2,     played:12,  streak:0, bp:0, change:0  },
  { id:10,   name:'Carina Dillmann',             gender:'female', tier:'silver',   points:31,     gain:3.5,   played:11,  streak:0, bp:0, change:0  },
  { id:11,   name:'Marcel Hölbl',                gender:'male',   tier:'silver',   points:29.5,   gain:1.5,   played:13,  streak:0, bp:0, change:0  },
  { id:12,   name:'Dominic Petritsch',           gender:'male',   tier:'silver',   points:26.5,   gain:2.5,   played:11,  streak:0, bp:0, change:0  },
  { id:13,   name:'Laetitia Föttinger',          gender:'female', tier:'silver',   points:26,     gain:2,     played:11,  streak:0, bp:0, change:0  },
  { id:14,   name:'Christoph Helmut Kopka',      gender:'male',   tier:'silver',   points:24.5,   gain:2,     played:11,  streak:0, bp:0, change:0  },
  { id:15,   name:'Andrea Stadler',              gender:'female', tier:'silver',   points:23,     gain:2,     played:11,  streak:0, bp:0, change:0  },
  { id:16,   name:'Thomas Wanek',                gender:'male',   tier:'silver',   points:20.5,   gain:4,     played:7,   streak:0, bp:0, change:0  },
  { id:17,   name:'Kerstin Aigner',              gender:'female', tier:'silver',   points:19,     gain:2.5,   played:7,   streak:0, bp:0, change:0  },
  { id:18,   name:'Amen Hussain',                gender:'male',   tier:'silver',   points:17,     gain:3.5,   played:6,   streak:0, bp:0, change:0  },
  { id:19,   name:'Christopher Pietschnig',      gender:'male',   tier:'silver',   points:17,     gain:2.5,   played:8,   streak:0, bp:0, change:0  },
  { id:20,   name:'Julia Boublik',               gender:'female', tier:'silver',   points:16.5,   gain:6,     played:7,   streak:0, bp:0, change:0  },
  { id:21,   name:'Christian Mehofer',           gender:'male',   tier:'silver',   points:16.5,   gain:2,     played:7,   streak:0, bp:0, change:0  },
  { id:22,   name:'Sammy',                       gender:'male',   tier:'silver',   points:14.5,   gain:2,     played:8,   streak:0, bp:0, change:0  },
  { id:23,   name:'Alex Weindl',                 gender:'male',   tier:'silver',   points:14,     gain:1.5,   played:7,   streak:0, bp:0, change:0  },
  { id:24,   name:'Leon Simic',                  gender:'male',   tier:'silver',   points:13,     gain:3,     played:6,   streak:0, bp:0, change:0  },
  { id:25,   name:'Samuel Ziselsberger',         gender:'male',   tier:'silver',   points:11,     gain:3,     played:5,   streak:0, bp:0, change:0  },
  { id:26,   name:'Markus Kerstin',              gender:'male',   tier:'silver',   points:10.5,   gain:2.5,   played:3,   streak:0, bp:0, change:0  },
  { id:27,   name:'Caspar de Maré',              gender:'male',   tier:'silver',   points:10,     gain:1,     played:4,   streak:0, bp:0, change:0  },
  { id:28,   name:'Luke Nemerski',               gender:'male',   tier:'silver',   points:10,     gain:4,     played:3,   streak:0, bp:0, change:0  },
  { id:29,   name:'Alex Rokas',                  gender:'male',   tier:'silver',   points:9.5,    gain:3,     played:4,   streak:0, bp:0, change:0  },
  { id:30,   name:'Asmin',                       gender:'female', tier:'silver',   points:9,      gain:2.5,   played:6,   streak:0, bp:0, change:0  },
  { id:31,   name:'Moritz',                      gender:'male',   tier:'silver',   points:9,      gain:1,     played:7,   streak:0, bp:0, change:0  },
  { id:32,   name:'Nina Koller',                 gender:'female', tier:'silver',   points:8.5,    gain:2.5,   played:4,   streak:0, bp:0, change:0  },
  { id:33,   name:'Fabian',                      gender:'male',   tier:'silver',   points:8,      gain:1.5,   played:5,   streak:0, bp:0, change:0  },
  { id:34,   name:'Lana',                        gender:'female', tier:'silver',   points:7.5,    gain:2,     played:3,   streak:0, bp:0, change:0  },
  { id:35,   name:'Adrian BabyNinja',            gender:'male',   tier:'silver',   points:7.5,    gain:2.5,   played:4,   streak:0, bp:0, change:0  },
  { id:36,   name:'Martin Petri',                gender:'male',   tier:'silver',   points:7,      gain:2.5,   played:3,   streak:0, bp:0, change:0  },
  { id:37,   name:'Lisa Riedl',                  gender:'female', tier:'silver',   points:6.5,    gain:2.5,   played:3,   streak:0, bp:0, change:0  },
  { id:38,   name:'Anna Thunder',                gender:'female', tier:'silver',   points:6.5,    gain:2,     played:4,   streak:0, bp:0, change:0  },
  { id:39,   name:'Lino Perner',                 gender:'male',   tier:'silver',   points:6,      gain:1,     played:3,   streak:0, bp:0, change:0  },
  { id:40,   name:'Matthias Friedmann',          gender:'male',   tier:'silver',   points:6,      gain:2,     played:4,   streak:0, bp:0, change:0  },
  { id:41,   name:'Wolfgang',                    gender:'male',   tier:'silver',   points:6,      gain:3,     played:2,   streak:0, bp:0, change:0  },
  { id:42,   name:'Marco Roll',                  gender:'male',   tier:'silver',   points:6,      gain:3,     played:3,   streak:0, bp:0, change:0  },
  { id:43,   name:'Jasmin Moser',                gender:'female', tier:'silver',   points:5,      gain:2.5,   played:2,   streak:0, bp:0, change:0  },
  { id:44,   name:'Tobias Myclubs',              gender:'male',   tier:'silver',   points:5,      gain:2.5,   played:2,   streak:0, bp:0, change:0  },
  { id:45,   name:'Michael Myclubs',             gender:'male',   tier:'silver',   points:5,      gain:3,     played:2,   streak:0, bp:0, change:0  },
  { id:46,   name:'Lisa Seeböck',                gender:'female', tier:'silver',   points:5,      gain:2.5,   played:2,   streak:0, bp:0, change:0  },
  { id:47,   name:'Richard Ninjas',              gender:'male',   tier:'silver',   points:5,      gain:3,     played:2,   streak:0, bp:0, change:0  },
  { id:48,   name:'Xaver',                       gender:'male',   tier:'silver',   points:4,      gain:4,     played:1,   streak:0, bp:0, change:0  },
  { id:49,   name:'Sophie',                      gender:'female', tier:'silver',   points:4,      gain:4,     played:1,   streak:0, bp:0, change:0  },
  { id:50,   name:'Akad Kara',                   gender:'male',   tier:'silver',   points:4,      gain:2,     played:3,   streak:0, bp:0, change:0  },
  { id:51,   name:'Sebastian Oberleitner',       gender:'male',   tier:'silver',   points:3.5,    gain:2.5,   played:2,   streak:0, bp:0, change:0  },
  { id:52,   name:'Pawel Czech',                 gender:'male',   tier:'silver',   points:3,      gain:1,     played:2,   streak:0, bp:0, change:0  },
  { id:53,   name:'Stanzi',                      gender:'female', tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:54,   name:'Kiki',                        gender:'female', tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:55,   name:'Benny',                       gender:'male',   tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:56,   name:'Susi Kopka',                  gender:'female', tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:57,   name:'Daniel Vondrasek',            gender:'male',   tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:58,   name:'Rory',                        gender:'male',   tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:59,   name:'Olivia',                      gender:'female', tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:60,   name:'Felix',                       gender:'male',   tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:61,   name:'Markus Myclubs',              gender:'male',   tier:'silver',   points:3,      gain:2,     played:2,   streak:0, bp:0, change:0  },
  { id:62,   name:'Linda Myclubs',               gender:'female', tier:'silver',   points:3,      gain:2,     played:2,   streak:0, bp:0, change:0  },
  { id:63,   name:'Matthias Marco Freund',       gender:'male',   tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:64,   name:'Victor Marco Freund',         gender:'male',   tier:'silver',   points:3,      gain:3,     played:1,   streak:0, bp:0, change:0  },
  { id:65,   name:'Branko Jovanovic',            gender:'male',   tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:66,   name:'Richard Holstein',            gender:'male',   tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:67,   name:'Berk',                        gender:'male',   tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:68,   name:'Marlene',                     gender:'female', tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:69,   name:'Alexandra',                   gender:'female', tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:70,   name:'Patrik',                      gender:'male',   tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:71,   name:'Steve Roll',                  gender:'male',   tier:'silver',   points:2.5,    gain:2.5,   played:1,   streak:0, bp:0, change:0  },
  { id:72,   name:'Martin Hermann',              gender:'male',   tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:73,   name:'Rebecca Hermann',             gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:74,   name:'Tia Szasz',                   gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:75,   name:'Lisa',                        gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:76,   name:'Christian Riedl',             gender:'male',   tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:77,   name:'Alex Rabl',                   gender:'male',   tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:78,   name:'Adrian 2',                    gender:'male',   tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:79,   name:'Rosa',                        gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:80,   name:'Verena',                      gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:81,   name:'Hannah',                      gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:82,   name:'Flo Hermann',                 gender:'male',   tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:83,   name:'Phoebe Myclubs',              gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:84,   name:'Lilli Huber',                 gender:'female', tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:85,   name:'Pascal Marco Freund',         gender:'male',   tier:'silver',   points:2,      gain:2,     played:1,   streak:0, bp:0, change:0  },
  { id:86,   name:'Joel',                        gender:'male',   tier:'silver',   points:1.5,    gain:1.5,   played:1,   streak:0, bp:0, change:0  },
  { id:87,   name:'Magdalena',                   gender:'female', tier:'silver',   points:1.5,    gain:1.5,   played:1,   streak:0, bp:0, change:0  },
  { id:88,   name:'Tanh Myclubs',                gender:'female', tier:'silver',   points:1.5,    gain:1.5,   played:1,   streak:0, bp:0, change:0  },
  { id:89,   name:'Emir Arzun Bruder',           gender:'male',   tier:'silver',   points:1.5,    gain:1.5,   played:1,   streak:0, bp:0, change:0  },
  { id:90,   name:'Demian Kerner',               gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:91,   name:'Johan Aninger',               gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:92,   name:'Larissa',                     gender:'female', tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:93,   name:'Lea Brunner',                 gender:'female', tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:94,   name:'Maximilian Floriani',         gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:95,   name:'Jed',                         gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:96,   name:'Naef',                        gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:97,   name:'Baby Dominik',                gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:98,   name:'Cim',                         gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:99,   name:'Nicole Myclubs',              gender:'female', tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
  { id:100,  name:'Raoul Myclubs',               gender:'male',   tier:'silver',   points:1,      gain:1,     played:1,   streak:0, bp:0, change:0  },
];

module.exports = { DEFAULT_PLAYERS };
